#
#  https://hub.docker.com/r/intel/oneapi-hpckit
#

FROM intel/oneapi-hpckit:2025.2.0-0-devel-ubuntu22.04


#  against WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
ARG DEBIAN_FRONTEND=noninteractive

RUN    apt update \
 &&    apt install -y unzip wget git  vim nano mc 

#          _ __ ___   ___  ___  ___  _ __  
#         | '_ ` _ \ / _ \/ __|/ _ \| '_ \ 
#         | | | | | |  __/\__ \ (_) | | | |
#         |_| |_| |_|\___||___/\___/|_| |_|
                      
ARG MESON_VERSION=1.9.0
ARG NINJA_VERSION=1.13.1

ADD https://github.com/mesonbuild/meson/releases/download/${MESON_VERSION}/meson-${MESON_VERSION}.tar.gz     /tmp/meson.tar.gz
ADD https://github.com/ninja-build/ninja/releases/download/v${NINJA_VERSION}/ninja-linux.zip                 /tmp/ninja-linux.zip

RUN  mkdir --parents /opt/meson  \
    &&  tar xf /tmp/meson.tar.gz --strip-components=1 -C /opt/meson \
    && chmod +x /opt/meson/meson.py \
    && ln -s /opt/meson/meson.py /opt/meson/meson \
    && unzip  /tmp/ninja-linux.zip -d /opt/meson \
    && rm /tmp/meson.tar.gz   /tmp/ninja-linux.zip
    
ENV PATH="/opt/meson:$PATH"

